name: Cloud check in action
on:
  push:
    branches:
      - main
  watch:
    types: started
  schedule:
    - cron: 35 3 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: init
      run: npm install
    - name: run
      id: run
      uses: nick-fields/retry@v2
      env:
        TY_USER_NAME: ${{secrets.TY_USER_NAME}}
        TY_PASSWORD: ${{secrets.TY_PASSWORD}}
        TY_FAMILY_ID: ${{secrets.TY_FAMILY_ID}}
        
        # Server
        SENDKEY: ${{secrets.SENDKEY}}


      with:
        timeout_minutes: 10
        max_attempts: 3
        command: npm start
